# Generated by Django 4.2 on 2024-01-03 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_event_summary'),
        ('meeting', '0004_alter_keyword_meeting_alter_news_meeting_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('audio', models.FileField(blank=True, null=True, upload_to='audio/')),
                ('text', models.FileField(blank=True, null=True, upload_to='text/')),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.event')),
            ],
        ),
    ]
