# Generated by Django 4.2 on 2024-01-03 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_meetingdetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetingdetail',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
