# Generated by Django 4.2 on 2024-01-04 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0006_alter_meetingdetail_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MeetingDetail',
        ),
    ]
