# Generated by Django 4.2 on 2024-01-05 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0008_rename_summary_news_news_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='news_summary',
        ),
        migrations.AddField(
            model_name='keyword',
            name='news_summary',
            field=models.TextField(null=True),
        ),
    ]
