# Generated by Django 4.2 on 2024-01-07 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_event_meeting_text'),
        ('meeting', '0009_remove_news_news_summary_keyword_news_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_title', models.TextField(null=True)),
                ('issues_progress', models.TextField(null=True)),
                ('situation_announcement', models.TextField(null=True)),
                ('agenda', models.TextField(null=True)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.event')),
            ],
        ),
    ]
