# Generated by Django 4.2 on 2024-01-06 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_event_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
