# Generated by Django 4.2 on 2024-01-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schedule", "0004_event_meeting_text"),
    ]

    operations = [
        migrations.CreateModel(
            name="FileModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="event_files/")),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="event",
            name="meeting_text",
        ),
        migrations.RemoveField(
            model_name="event",
            name="summary",
        ),
        migrations.AddField(
            model_name="event",
            name="files",
            field=models.ManyToManyField(to="schedule.filemodel"),
        ),
    ]
