# Generated by Django 4.2 on 2024-01-08 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_filemodel_remove_event_meeting_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
